### PR TITLE
Updates to CLI

### PR DESCRIPTION
**Pull request by manuGil**
- Include examples in the distribution
- Add command to summon examples using `aeolis-examples <path/to/directory>` from the CLI
- Includes a demo for a new CLI using **typer**; this can be accessed on the CLI by using `aeolis-new --help`
- Solves #158

### CODE REVIEW

**Comment by manuGil** [comment]
> Changes brake the editable installation:
> 
> ```python
> ERROR: /home/manuel/Documents/devel/aeolis-python/dist/aeolis-2.1.3-py3-none-any.whl is not a valid editable requirement. 
>  It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, 
>  bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, 
>  svn+http, svn+https, svn+svn, svn+file).
> ```
> 
> Read: [pfmoore/editables#20](https://github.com/pfmoore/editables/issues/20)

This was fixed by moving the example directory into the package's root. This solves the problem and is also good practice when data files need to be included as part of a package.

File: aeolis/console_typer.py [hunk 1]
```diff
@@ -0,0 +1,150 @@
...
+
+import os
+import logging
+import shutil
+import numpy as np
+import aeolis as aeolis_pkg
+from aeolis.model import AeoLiSRunner, WindGenerator
+
+import typer
+from typing import Annotated, Optional
```
Comment (niketagrawal) [inline aeolis/console_typer.py:36]: This needs Python>=3.9

Testing the update CLI triggers the following error on Python 3.8.
```
$ aeolis-new --help
Traceback (most recent call last):
  File "/../venvs/../bin/aeolis-new", line 5, in <module>
	from aeolis.console_typer import app
  File "/../venvs/../lib/python3.8/site-packages/aeolis/console_typer.py", line 36, in <module>
	from typing import Annotated, Optional
ImportError: cannot import name 'Annotated' from 'typing' (/usr/lib/python3.8/typing.py)
```
[Annotated is introduced in Python 3.9](https://docs.python.org/3/whatsnew/3.9.html#typing)

Changes work fine on Python 3.9

File: docs/tutorials/2D-parabolic.rst [hunk 2]
```diff
@@ -1,10 +1,15 @@
-2D parabolic dune model
+Parabolic dune model
```
Comment (niketagrawal) [inline docs/tutorials/2D-parabolic.rst:1]: The parabolic dune example can't be run in a few minutes by users on their laptops.

```
        Time elapsed / Total time / Time remaining / Average Timestep
000.0%       0:00:03 / 1 day, 6:37:52 / 1 day, 6:37:49 / 3600.0
```

@Sierd , we need to remove or replace this example with another one that can be run quickly by users. Do you have a replacement in mind?

Comment (niketagrawal) [reply docs/tutorials/2D-parabolic.rst:1]: We agree on keeping the parabolic dune example because trying out examples with different run times will help give users a clearer picture of simulating different models with aeolis.

**Comment by niketagrawal** [comment]
Code changes in new commits:

- Old command line interface is replaced with new command line interface
- GitHub actions workflow for running automated tests is renamed to run-tests.yml. The old name python-app.yml did not convey the correct meaning.
- Unit tests added for console.py module
- Minimum version of Python bumped to 3.9 from 3.8 because typing.Annotated needs Python>=3.9

**Review by Sierd — APPROVED** [review]
